# Generated by Django 5.1.6 on 2025-02-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_service',
            field=models.CharField(default='fas fa-paint-roller', max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='Service sans titre', max_length=200, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
        ),
    ]
