# Generated by Django 5.1.6 on 2025-02-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_icon_service_service_title_servicefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('residential', 'Résidentiel'), ('commercial', 'Commercial'), ('industrial', 'Industriel'), ('exterior', 'Extérieur'), ('interior', 'Intérieur'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie'),
        ),
    ]
