# Generated by Django 5.1.6 on 2025-02-23 12:07

import colorfield.fields
import django.db.models.deletion
import django_ckeditor_5.fields
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorfield.fields.ColorField(default='#424e55', image_field=None, max_length=25, samples=None, verbose_name='couleur primaire')),
                ('secondary_color', colorfield.fields.ColorField(default='#5a666e', image_field=None, max_length=25, samples=None, verbose_name='couleur secondaire')),
                ('accent_color', colorfield.fields.ColorField(default='#68a138', image_field=None, max_length=25, samples=None, verbose_name="couleur d'accent")),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100, verbose_name='police principale')),
                ('heading_font', models.CharField(default='Arial, sans-serif', max_length=100, verbose_name='police des titres')),
                ('base_font_size', models.CharField(default='16px', max_length=10, verbose_name='taille de police de base')),
                ('custom_css', models.TextField(blank=True, verbose_name='CSS personnalisé')),
            ],
            options={
                'verbose_name': 'style du site',
                'verbose_name_plural': 'styles du site',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='contenu')),
                ('template', models.CharField(choices=[('default', 'Template par défaut'), ('home', "Page d'accueil"), ('services', 'Page de services'), ('contact', 'Page de contact')], default='default', max_length=50, verbose_name='template')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='titre SEO')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='description SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='mots-clés SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='ordre')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='config.menu')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='config.page')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'ordering': ['order'],
            },
        ),
    ]
