# Generated by Django 5.1.6 on 2025-02-23 16:11

import colorfield.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_page_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='css_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='classe CSS'),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, help_text='Description pour les menus déroulants', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, help_text="Classe d'icône FontAwesome", max_length=50, verbose_name='icône'),
        ),
        migrations.AddField(
            model_name='menu',
            name='target',
            field=models.CharField(choices=[('_self', 'Même fenêtre'), ('_blank', 'Nouvelle fenêtre')], default='_self', max_length=20, verbose_name='cible'),
        ),
        migrations.AddField(
            model_name='page',
            name='css_class',
            field=models.CharField(blank=True, help_text='Classes CSS supplémentaires pour cette page', max_length=100, verbose_name='classe CSS'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, verbose_name="page d'accueil"),
        ),
        migrations.AddField(
            model_name='page',
            name='js_code',
            field=models.TextField(blank=True, help_text='Code JavaScript spécifique à cette page', verbose_name='code JavaScript'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image pour les réseaux sociaux', upload_to='pages/og/', verbose_name='image OG'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_nav',
            field=models.BooleanField(default=True, verbose_name='afficher dans la navigation'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='body_line_height',
            field=models.CharField(default='1.6', max_length=10, verbose_name='hauteur de ligne du corps'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='container_width',
            field=models.CharField(default='1200px', max_length=10, verbose_name='largeur du conteneur'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='grid_gutter',
            field=models.CharField(default='30px', max_length=10, verbose_name='gouttière de grille'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='heading_color',
            field=colorfield.fields.ColorField(default='#424e55', image_field=None, max_length=25, samples=None, verbose_name='couleur des titres'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='heading_line_height',
            field=models.CharField(default='1.2', max_length=10, verbose_name='hauteur de ligne des titres'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='link_color',
            field=colorfield.fields.ColorField(default='#68a138', image_field=None, max_length=25, samples=None, verbose_name='couleur des liens'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='mobile_breakpoint',
            field=models.CharField(default='768px', max_length=10, verbose_name='point de rupture mobile'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='tablet_breakpoint',
            field=models.CharField(default='992px', max_length=10, verbose_name='point de rupture tablette'),
        ),
        migrations.AddField(
            model_name='sitestyle',
            name='text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='couleur du texte'),
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=255, verbose_name='commentaire')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='config.page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
