# Generated by Django 5.1.6 on 2025-02-24 18:14

import django.db.models.deletion
import django_ckeditor_5.fields
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_menu_css_class_menu_description_menu_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=200, unique=True, verbose_name='Old Path')),
                ('new_path', models.CharField(max_length=200, verbose_name='New Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_homepage',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='page',
            name='template',
        ),
        migrations.AddField(
            model_name='page',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='page',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='config.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published at'),
        ),
        migrations.AddField(
            model_name='page',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='page',
            name='schema_description',
            field=models.TextField(blank=True, verbose_name='Schema Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='schema_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Schema Name'),
        ),
        migrations.AddField(
            model_name='page',
            name='schema_type',
            field=models.CharField(default='WebPage', max_length=50, verbose_name='Schema Type'),
        ),
        migrations.AddField(
            model_name='page',
            name='tree_id',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='Meta Description SEO'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta Title SEO'),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='og_images/', verbose_name='OG Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='config.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_configs', to='config.page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('rich_text', 'Rich Text'), ('image', 'Image'), ('gallery', 'Gallery'), ('video', 'Video'), ('file', 'File'), ('map', 'Map')], max_length=20, verbose_name='Field Type')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='config.page')),
            ],
            options={
                'unique_together': {('page', 'name')},
            },
        ),
    ]
