# Generated by Django 5.1.6 on 2025-02-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_redirect_remove_page_is_homepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='URL Canonique'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_type',
            field=models.CharField(default='website', max_length=50, verbose_name='OG Type'),
        ),
        migrations.AddField(
            model_name='page',
            name='robots',
            field=models.CharField(default='index,follow', max_length=50, verbose_name='Robots'),
        ),
    ]
