# Generated by Django 5.1.6 on 2025-02-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_page_canonical_url_page_og_type_page_robots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['group', 'order', 'name'], 'verbose_name': 'Champ personnalisé', 'verbose_name_plural': 'Champs personnalisés'},
        ),
        migrations.AlterModelOptions(
            name='fieldgroup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Groupe de champs', 'verbose_name_plural': 'Groupes de champs'},
        ),
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ['-created_at'], 'verbose_name': 'Redirection', 'verbose_name_plural': 'Redirections'},
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fieldgroup',
            name='page',
        ),
        migrations.AddField(
            model_name='customfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Pour le type "choix", entrez les options séparées par des virgules', verbose_name='Choix'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='config.fieldgroup', verbose_name='Groupe'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Obligatoire'),
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='page',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Date et heure de publication programmée', null=True, verbose_name='Programmé pour'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texte'), ('textarea', 'Zone de texte'), ('number', 'Nombre'), ('date', 'Date'), ('boolean', 'Booléen'), ('choice', 'Choix'), ('file', 'Fichier'), ('image', 'Image')], max_length=20, verbose_name='Type de champ'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='fieldgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du groupe'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(max_length=200, verbose_name='Nouveau chemin'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ancien chemin'),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.customfield')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='config.page')),
            ],
            options={
                'verbose_name': 'Valeur de champ personnalisé',
                'verbose_name_plural': 'Valeurs de champs personnalisés',
                'unique_together': {('field', 'page')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, through='config.CustomFieldValue', to='config.customfield'),
        ),
        migrations.DeleteModel(
            name='PageVersion',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='value',
        ),
    ]
