# Generated by Django 5.1.6 on 2025-02-16 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_companyinfo_alter_contact_options_contact_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(default='Vile', help_text='Ville', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='postal_code',
            field=models.CharField(default='00000', help_text='Code postal', max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_postal_code', message='Le code postal doit contenir exactement 5 chiffres.', regex='^\\d{5}$')], verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(help_text='Email', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='latitude',
            field=models.FloatField(help_text='Latitude', verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='longitude',
            field=models.FloatField(help_text='Longitude', verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='opening_hours',
            field=models.TextField(help_text="Horaires d'ouverture", verbose_name="Horaires d'ouverture"),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(help_text='Téléphone', max_length=20, verbose_name='Téléphone'),
        ),
    ]
