# Generated by Django 5.1.6 on 2025-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'À propos de nous',
                'verbose_name_plural': 'À propos de nous',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('image', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
            },
        ),
    ]
