# Generated by Django 5.1.6 on 2025-02-22 16:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReviewsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Votre clé API Google Places', max_length=255, verbose_name='clé API Google')),
                ('place_id', models.CharField(help_text="L'ID Google My Business de votre établissement", max_length=255, verbose_name="ID de l'établissement")),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='dernière synchronisation')),
                ('auto_import', models.BooleanField(default=True, help_text='Importer automatiquement les nouveaux avis Google', verbose_name='importation automatique')),
                ('min_rating', models.IntegerField(default=4, help_text="Note minimum pour l'importation automatique", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note minimum')),
            ],
            options={
                'verbose_name': 'configuration Google Reviews',
                'verbose_name_plural': 'configurations Google Reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date_posted', '-rating'], 'verbose_name': 'témoignage', 'verbose_name_plural': 'témoignages'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='position',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(blank=True, help_text="Nom de l'auteur", max_length=100, null=True, verbose_name="nom de l'auteur"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='titre/profession'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='entreprise'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date_imported',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'importation"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de publication'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID de référence de la plateforme externe', max_length=100, verbose_name='ID externe'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='mis en avant'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='platform',
            field=models.CharField(choices=[('google', 'Google'), ('site', 'Site Web'), ('facebook', 'Facebook')], default='google', max_length=20, verbose_name='plateforme'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='témoignage'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='vérifié'),
        ),
    ]
