# Generated by Django 5.1.6 on 2025-02-22 16:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_googlereviewssettings_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=True, help_text="Si le témoignage est actifdans la page d'accueil", verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_image',
            field=models.ImageField(blank=True, help_text="Photo de l'auteur", null=True, upload_to='testimonials/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(blank=True, default=0, help_text="Nom de l'auteur", max_length=100, verbose_name="nom de l'auteur"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_title',
            field=models.CharField(blank=True, help_text="Titre/profession de l'auteur", max_length=100, verbose_name='titre/profession'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, help_text="Entreprise de l'auteur", max_length=100, verbose_name='entreprise'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='date_imported',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date d'importation du témoignagedans la base de données", verbose_name="date d'importation"),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date de publication du témoignagedans la page d'accueil", verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False, help_text="Si le témoignage est mis en avantdans la page d'accueil", verbose_name='mis en avant'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='platform',
            field=models.CharField(choices=[('google', 'Google'), ('site', 'Site Web'), ('facebook', 'Facebook')], default='google', help_text="Plateforme de l'auteur", max_length=20, verbose_name='plateforme'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, help_text="Note de l'auteur (entre 1 et 5)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(blank=True, default=0, help_text="Témoignage de l'auteur", verbose_name='témoignage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='verified',
            field=models.BooleanField(default=False, help_text="Si le témoignage est vérifiédans la page d'accueil", verbose_name='vérifié'),
        ),
    ]
