# Generated by Django 5.1.6 on 2025-02-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_account_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
