# Generated by Django 5.1.6 on 2025-02-21 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_failed_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='frist_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_locked',
            field=models.BooleanField(default=False, verbose_name='account locked'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='failed login attempts'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Ce champ doit contenir uniquement des lettres, des espaces et des tirets.', regex='^[a-zA-ZÀ-ÿ\\s\\-]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='two-factor authentication'),
        ),
    ]
