# Generated by Django 5.1.6 on 2025-02-21 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_frist_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'verbose_name': 'inscription newsletter', 'verbose_name_plural': 'inscriptions newsletter'},
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='created_at',
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='subscribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="date d'inscription"),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
    ]
