# Generated by Django 5.1.6 on 2025-02-21 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newslettersubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'profil client', 'verbose_name_plural': 'profils clients'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(blank=True, max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code Postal'),
        ),
    ]
