# Generated by Django 5.1.6 on 2025-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('service', models.CharField(max_length=200, verbose_name='Service demandé')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface (m²)')),
                ('details', models.TextField(verbose_name='Détails supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traité'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
    ]
