# Generated by Django 5.1.6 on 2025-02-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commande minimum')),
                ('lead_time', models.IntegerField(default=1, verbose_name='Délai de livraison (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='PaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='quotes.paintcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.JSONField(default=dict, verbose_name='Caractéristiques')),
                ('technical_sheet', models.FileField(blank=True, upload_to='technical_sheets/')),
                ('finish', models.CharField(choices=[('matte', 'Mat'), ('satin', 'Satin'), ('gloss', 'Brillant'), ('semi_gloss', 'Semi-brillant')], max_length=20, verbose_name='Finition')),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Couverture (m²/L)')),
                ('drying_time', models.CharField(max_length=100, verbose_name='Temps de séchage')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base')),
                ('stock_quantity', models.IntegerField(verbose_name='Quantité en stock')),
                ('min_stock', models.IntegerField(verbose_name='Stock minimum')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.paintcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paints', to='quotes.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PaintVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=20, verbose_name='Code couleur')),
                ('color_name', models.CharField(max_length=100, verbose_name='Nom couleur')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taille (L)')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ajustement de prix')),
                ('stock_quantity', models.IntegerField(verbose_name='Quantité en stock')),
                ('image', models.ImageField(upload_to='paint_variants/')),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quotes.paint')),
            ],
        ),
    ]
