# Generated by Django 5.1.6 on 2025-02-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
    ]
