# Generated by Django 5.1.6 on 2025-02-18 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_paintcategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quotes/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='area',
            new_name='area_size',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='details',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='service',
        ),
        migrations.AddField(
            model_name='quote',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='quote',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Budget estimé'),
        ),
        migrations.AddField(
            model_name='quote',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='quote',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Postal'),
        ),
        migrations.AddField(
            model_name='quote',
            name='preferred_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date préférée'),
        ),
        migrations.AddField(
            model_name='quote',
            name='project_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description du projet'),
        ),
        migrations.AddField(
            model_name='quote',
            name='service_type',
            field=models.CharField(choices=[('interior', 'Peinture Intérieure'), ('exterior', 'Peinture Extérieure'), ('commercial', 'Peinture Commerciale'), ('industrial', 'Peinture Industrielle'), ('decorative', 'Peinture Décorative')], default='interior', max_length=200, verbose_name='Type de Service'),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_review', 'En cours de révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='quote',
            name='reference_photos',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='quotes.quotephoto'),
        ),
        migrations.CreateModel(
            name='QuoteStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_review', 'En cours de révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('canceled', 'Annulé')], max_length=20)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='quotes.quote')),
            ],
        ),
    ]
