# Generated by Django 5.1.6 on 2025-02-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_quote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
    ]
