# Generated by Django 5.1.6 on 2025-02-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='description',
        ),
        migrations.AddField(
            model_name='color',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='color',
            name='rgb_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code RGB'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, verbose_name='Code Hexadécimal'),
        ),
    ]
