# Generated by Django 5.1.6 on 2025-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_remove_color_description_color_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='category',
        ),
        migrations.AddField(
            model_name='color',
            name='color_type',
            field=models.CharField(choices=[('warm', 'Chaude'), ('cool', 'Froide'), ('neutral', 'Neutre')], default='neutral', max_length=10, verbose_name='Type de Couleur'),
        ),
        migrations.AddField(
            model_name='color',
            name='light_reflectance_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valeur de Réflectance Lumineuse'),
        ),
    ]
